### ISSUE TITLE
Styling based on tags doesn't work

### ISSUE THREAD

**Issue by madvas** [FundingCircle/fc4-framework#290]
If I want to change styling of an element based on its tag, it doesn't work.

Example: 
I want to differentiate existing system by color.
(Changing order of styling entries doesn't help)
```
link__for_use_with: https://structurizr.com/express
link__diagram_scheme_description: https://c4model.com/
---
type: System Context
scope: My System
description: System Context diagram for My System

elements:
- type: Person
  name: User
  description: A user using My System.
  position: '1025,50'
- type: Software System
  name: My System
  description: Good System is My.
  position: '1000,1000'
- type: Software System
  name: Some Existing System
  description: Existing many years already
  position: '1800,600'
  tag: Existing System

relationships:
- source: User
  description: creates or uses 
  destination: My System
  technology: Browser
- source: User
  description: Submits transactions
  destination: Some Existing System
  technology: Browser

styles:
- type: element
  tag: Element
  color: '#ffffff'
- type: element
  tag: Person
  background: '#08427b'
  shape: Person
- type: element
  tag: Existing System
  background: '#999999'  
- type: element
  tag: Software System
  background: '#1168bd'

size: A5_Landscape
```

Results in:
![image](https://user-images.githubusercontent.com/3857155/80053683-b390b980-8547-11ea-95f5-fcb97db2d440.png)
